### ISSUE TITLE
vmhgfs does not apply cleanly

### ISSUE THREAD

**Issue by floobit** [rasa/vmware-tools-patches#25]
Thanks for some great software!  I have some little things: 

I have a vote for a design change: I prefer to not run vmware-install.pl and vmware-tools-config.pl with defaults for a couple reasons (I don't always remember the packages I need when setting up a new system, and the installer prompts me, I don't want all the kernel modules, etc).  If I just run untar-and-patch-and-compile.sh as in the instructions and not all packages are installed, it fails hard and I have to clean up.  Not a big deal, just a suggestion.  

I don't use shared folders, but in the interest of supporting the developer, I had an error with hgfs.  I'm on the latest kernel of fedora 21: 3.18.7-200.fc21.x86_64, and running the patches yields: 

=== Patching ./VMwareTools-9.9.0-2304977.tar.gz ...

*** Skipping vmhgfs/vmhgfs-d_set_type-kernel-3.18.1-tools-9.6.1.patch: did not apply cleanly
*** Skipping vmhgfs/vmhgfs-d_count-kernel-3.11-tools-9.6.0.patch: did not apply cleanly
*** Skipping vmhgfs/vmhgfs-vfs_readlink-kernel-3.16-tools-9.6.2.patch: did not apply cleanly
*** Skipping vmhgfs/patch_inode.c.patch: did not apply cleanly
*** Applying vmhgfs/vmhgfs-d_alias-kernel-3.17.7-tools-9.9.0.patch ...
patching file inode.c
*** Skipping vmhgfs/compat_dcache.h.patch: did not apply cleanly
*** Skipping vmhgfs/vmhgfs-rename_deprecated-kernel-3.18.1-tools-9.6.1.patch: did not apply cleanly
*** Skipping vmhgfs/vmware9.compat_mm.patch: did not apply cleanly
*** Skipping vmhgfs/vmhgfs-wait_on_bit-kernel-3.17-tools-9.6.2.patch: did not apply cleanly
*** Skipping vmhgfs/vmhgfs-uid-gid-kernel-3.12-tools-9.6.1.patch: did not apply cleanly
*** Applying vmhgfs/vmhgfs-3.15-vfs_readlink.patch ...
patching file link.c
Hunk #1 succeeded at 160 (offset 9 lines).
Hunk #2 succeeded at 200 (offset 11 lines).
*** Applying vmhgfs/vmhgfs-smp_mb_before_clear_bit-3.18-tools-9.9.0.patch ...
patching file page.c
*** Applying vmci/vmware9.k3.8rc4.patch ...
patching file linux/driver.c
Reversed (or previously applied) patch detected!  Assuming -R.
Hunk #1 succeeded at 128 with fuzz 1 (offset 4 lines).
Hunk #2 succeeded at 1745 (offset -5 lines).
Hunk #3 succeeded at 1976 (offset -2 lines).
*** Applying vmblock/vmblock.3.11.patch ...
patching file linux/file.c
*** Applying vmblock/vmblock.3.10.patch ...
patching file linux/control.c
*** Applying vmblock/vmblock-vfs_readlink-kernel-3.15-tools-9.6.2.patch ...
patching file linux/inode.c
Hunk #1 succeeded at 177 (offset -1 lines).
*** Applying vsock/vsock-sk_data_ready-kernel-3.15-tools-9.6.2.patch ...
patching file linux/notify.c
patching file linux/notifyQState.c

**Comment by rasa** [comment]
Good point. The [README](../blob/master/README.md#quick-start) does not mention you can apply the patches but *not* run the `vmware-install.pl`, via [untar-and-patch.sh](../blob/master/untar-and-patch.sh)

**Comment by floobit** [comment]
Yes, this is what I ended up doing, though I had to remove lines 41-43 in
that script (they removed the patched tools package that I wanted to
install).  You could also run a prompt at the beginning of the compile
script to ask the user whether they want to run the compile with defaults.

I was thinking about this further, and if you wanted to make your package
even more user-friendly for rhel-variant users, you could also add some
code to the scripts that installs the prereqs.  For instance, you could
insert

if [ -e /etc/redhat-release ]; then echo "I've identified your system as
RHEL-compatible.  Now attempting to install vmware-tools dependencies:";
sudo yum -y install make perl gcc kernel-devel kernel-headers
glibc-headers; fi


between lines 33 and 34 of untar-and-patch.sh and
untar-and-patch-and-compile.sh.

Checking for the existence of /etc/redhat-release is not a perfect way to
identify whether an OS is a rhel-variant, but I would say that anyone who
creates /etc/redhat-release on a different distro should expect some wacky
behavior with distro id processes.

**Comment by anodynos** [comment]
See https://github.com/rasa/vmware-tools-patches/issues/29#issuecomment-76469889 - it worked for both 3.16 (Ubuntu 14.10) & 3.13 (Ubuntu 14.04)

**Comment by rasa** [comment]
Fixed in https://github.com/rasa/vmware-tools-patches/commit/192e3b78b94cfa872d45043d671fe0cb4572b714
