### ISSUE TITLE
Ubuntu 14.04.02 vmhgfs compile failure (VMwareTools-9.9.2-2496486)

### ISSUE THREAD

**Issue by eborshch** [rasa/vmware-tools-patches#29]
Hello!

I cannot compile the latest VMwareTools-9.9.2-2496486 (neither patched not original) on Ubuntu 14.04.02 with latest  Linux kernel (3.13.0-46). It raises the following error: 

```
 from /tmp/modconfig-qqjwHn/vmhgfs-only/inode.c:29:
/tmp/modconfig-qqjwHn/vmhgfs-only/inode.c: In function ‘HgfsPermission’:
include/linux/kernel.h:793:27: error: ‘struct dentry’ has no member named ‘d_alias’
  const typeof( ((type *)0)->member ) *__mptr = (ptr); \
```

The complete output can be found here https://gist.github.com/eborshch/cd6f430bf6771e33e5cf. I've noticed that there is a recent fix (https://github.com/rasa/vmware-tools-patches/pull/27) for the similar issue, though it does not solve this particular issue as it has been already merged into the master when I've tried it. 

Any hints? 

Thank you in advance!

Best,
Eugene

p.s. it looks like this issue has been already reported to VMWare https://communities.vmware.com/message/2477575

**Comment by rasa** [comment]
I'm looking into this now, and will let you know what I discover.

**Comment by vschoener** [comment]
Same issue for me on Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux

I try to use your patch install but the problem still persist.

(I already commented for another issue)

**Comment by vschoener** [comment]
Ok so I succeed with hgfs installation.

I uncompressed the "vmware-tools-distrib/lib/modules/source/vmhgfs.tar" with "tar cvf" command
then I used this command in my vim editor : ":%s/d_alias/d_u.d_alias/g" to replace any d_alias with his own new structure.
And finally just compress back the folder with : "tar cvf vmhgfs.tar vmhgfs-only" command

I restart the installer from the vmware-tools-distrib folder and now I can access to my folder.

The VMwareTools version is : VMwareTools-9.9.2-2496486.tar.gz

Hope It could help some of you :)

**Comment by anodynos** [comment]
I have the same here problem  **Kubuntu 14.04 (3.13.0-46-generic) & VMWare Workstation 11.1 & VMwareTools-9.9.2-2496486.tar.gz**
With the previous kernel **3.13.0-45 & VMwareTools-9.9.0** hgfs was working just fine (having applied the patch back in December).

**Comment by eborshch** [comment]
@vschoener thanks a bunch! It works!

**Comment by vschoener** [comment]
@eborshch You're welcome, I forgot to mention the file to edit "inode.c" But you found out :)

**Comment by anodynos** [comment]
@vschoener 
> I used this command in my vim editor : ":%s/d_alias/d_u.d_alias/g" to replace any d_alias with his own new structure. The file to edit is 'inode.c'

Can you please elaborate *with his own new structure* ? What string did you replace `d_alias` with ?

**Comment by vschoener** [comment]
I replaced d_alias to d_u.d_alias because this variable has been moved the "dentry" structure.

**Comment by LukeMauldin** [comment]
Following @vschoener instructions worked for me on Ubuntu 14.10.

**Comment by anodynos** [comment]
Thanks @vschoener - it worked great! 
FYI I did it on `Kubuntu 14.10 x64` with kernel `3.16.0-31-generic`.

**Comment by henrylee18** [comment]
@vschoener thanks for the tip and it works!

**Comment by bentoner** [comment]
Thank you. This fixes shared folders for me on Ubuntu 14.04 with VMwareTools-9.9.0-2304977 on Workstation 11.0.0.

**Comment by vschoener** [comment]
Thanks you all, I'm glad this fix is helping everyone :)

**Comment by tuongngoc** [comment]
It works fine for me too.

I run this

#!/bin/sh -x
cd /usr/lib/vmware-tools/modules/source
tar xf vmhgfs.tar
grep -q d_u.d_alias vmhgfs-only/inode.c && echo "already patched" && exit 0
sed -i -e s/d_alias/d_u.d_alias/ vmhgfs-only/inode.c
cp -p vmhgfs.tar vmhgfs.tar.orig
tar cf vmhgfs.tar vmhgfs-only
vmware-config-tools.pl -d -m

NOTE: this makes the tools incompatible with older kernel versions, i.e. 3.13.0-45.

**Comment by rasa** [comment]
@eborshch: How did you get kernel 3.13.0, as 3.16.0 is the default, per https://wiki.ubuntu.com/TrustyTahr/ReleaseNotes#Linux_kernel_3.16 . 

Also, I've installed both 
http://releases.ubuntu.com/trusty/ubuntu-14.04.2-server-amd64.iso and
http://cdimage.ubuntu.com/ubuntu-server/trusty/daily/current/trusty-server-amd64.iso
using [VMwareTools-9.9.2-2496486.tar.gz](https://softwareupdate.vmware.com/cds/vmw-desktop/fusion/7.1.1/2498930/packages/com.vmware.fusion.tools.linux.zip.tar), and always get kernel 3.16.0 and did not encounter any issues.

**Comment by ashb** [comment]
This fix still didn't work for me on Ubuntu 12.02 with linux-generic-lts-trusty (kernel 3.13.0-46) and I had to just hack the patch by adding a custom patch like this:

```patch
cat > patches/vmhgfs/99-vmhgfs-inode-hack-hack-bodge.patch   <<EOF
--- vmhgfs-only/inode.c.oirg    2015-03-06 14:56:04.344130628 +0000
+++ vmhgfs-only/inode.c 2015-03-06 14:56:14.583830707 +0000
@@ -1922,11 +1922,7 @@
                            p,
 #endif
                            &inode->i_dentry,
-#if LINUX_VERSION_CODE < KERNEL_VERSION(3, 18, 1) && !defined(__GENKSYMS__) && !defined(D_ALIAS_IS_A_MEMBER_OF_UNION_D_U)
-                           d_alias) {
-#else
                            d_u.d_alias) {
-#endif
          int dcount = hgfs_d_count(dentry);
          if (dcount) {
             LOG(4, ("Found %s %d \n", dentry->d_name.name, dcount));
@@ -1979,11 +1975,7 @@
       /* Find a dentry with valid d_count. Refer bug 587879. */
       list_for_each(pos, &inode->i_dentry) {
          int dcount;
-#if LINUX_VERSION_CODE < KERNEL_VERSION(3, 18, 1) && !defined(__GENKSYMS__) && !defined(D_ALIAS_IS_A_MEMBER_OF_UNION_D_U)
-         struct dentry *dentry = list_entry(pos, struct dentry, d_alias);
-#else
          struct dentry *dentry = list_entry(pos, struct dentry, d_u.d_alias);
-#endif
          dcount = hgfs_d_count(dentry);
          if (dcount) {
             LOG(4, ("Found %s %d \n", (dentry)->d_name.name, dcount));
EOF
```

With this done I get teh vmhgfs module compiled and loaded.

**Comment by rasa** [comment]
@ashb That's weird. What VMware Tools version did you use?

**Comment by ashb** [comment]
I thought it was 9.6.2, but vmware-toolbox-cmd --version says 9.9.2 so I'm trying again.

**Comment by cty12** [comment]
@vschoener 

So just **replace the 'd_alias'** will be fine? Do I have to patch the code using the patch provided in this repo first?

Many thanks.

**Comment by frol** [comment]
@rasa It seems that Ubuntu team has backported some features from 3.17+ to LTS kernels (3.13.0-46, 3.16.0-31 and probably some other). I can confirm that applying the patch without a check for 3.18.1 kernel works for me on 3.13.0-46 (3.13.0-45 worker well without the patch).

**Comment by vschoener** [comment]
@cty12 I didn't patch anything according to the available patch here.
I just replaced the 'd_alias' and everything works fine.
(My kernel is 3.2.X)

**Comment by rasa** [comment]
Fixed in https://github.com/rasa/vmware-tools-patches/commit/192e3b78b94cfa872d45043d671fe0cb4572b714#

**Comment by 130s** [comment]
Confirmed that 192e3b7 works. Thank you for the work @rasa and all.

3.13.0-46-generic
Host: Ubuntu 14.04 64b
Guest: Ubuntu 12.04 64b

**Comment by mouse07410** [comment]
@vschoener, you're great! Thank you for saving my Ubuntu 14.10 LTS!

**Comment by suntong001** [comment]
Thank you @vschoener, works great for

VMwareTools-9.9.2-2496486 for  
guest: Ubuntu 14.10  
under VMware Workstation for Windows v11.1.0.2496824

**Comment by pscorrigan** [comment]
@vschoener -  
Many thanks for this ... your fix saved me time ... and a headache ! ...

This fix works perfectly for 
VMware Tools 9.6.2.31837 (build-1688356)
guest Ubuntu 12.04.5 LTS
with kernel 3.13.0-48-generic x86_64
under VMware Player 6.0.4 build-2249910 for Windows 7 Ultimate

**Comment by pscorrigan** [comment]
@vschoener -

Further note ...

This fix works also works perfectly for: 
VMware Tools 9.6.2.31837 (build-1688356)
guest Ubuntu 14.04.2 LTS (trusty)
with kernel 3.13.0-48-generic x86_64
under VMware Player 6.0.4 build-2249910 for Windows 7 Ultimate

... thanks again!

**Comment by phlegx** [comment]
@tuongngoc thx! Yout shell script works for me.

**Comment by yakovkeselman** [comment]
@tuongngoc: many thanks! Your shell script worked for me too! Great job!

**Comment by papabasile** [comment]
@tuongngoc Thanks! The script worked fine for me too!

**Comment by rasa** [comment]
Is everyone implying that master is broken?

**Comment by jverhoeven** [comment]
@vschoener

Great stuff. Fix works fine! Shame on VMWare for not fixing this immediately. Really: 2 replaces in one inode.c file?

**Comment by vschoener** [comment]
@jverhoeven : You're welcome :) Indeed, it's shame to let this broken.. But now there is a great community to fix the problem and make people happy :)

**Comment by ethanlu2** [comment]
@vschoener  Thanks a lot. It helped!

**Comment by Cyber4** [comment]
Hopefully this works for me when I get home.  Have to reinstall my entire VM after screwing up the boot trying to fox this problem.  Using Ubuntu 15.04

**Comment by armanshahrisa** [comment]
Thanks a lot! It worked for me! I was getting crazy!!

**Comment by au10tic** [comment]
Using lubuntu 14.04.2 and replacing d_alias does not work for me.

**Comment by william-dowling** [comment]
@tuongngoc and @vschoener  Your tweak worked great for me with this guest setup
$ uname -a
Linux desktop 3.2.0-85-generic #122-Ubuntu SMP Tue May 26 16:15:25 UTC 2015 i686 i686 i386 GNU/Linux
Thanks!

**Comment by ehallander9591** [comment]
I am glad I found this thread of discussion. It worked for me.

**Comment by pgiu** [comment]
Happened the same to me today. 
My configurations: 
Windows 7 Host 
Ubuntu 14.04 w/ 3.13.0-52 kernel
Vmware 10.0.6 with Tools 9.6.5

I had the "d_alias" issue but the patches on the "patches" directory didn't solve the problem. 
Instead I got a new problem saying that there was a problem with a structure called DENTRY.

I ended up looking for a patch that had to do with the DENTRY struct and copied to the same patch directory with a name that matched my vmware tools version. I don't know how if that's the proper way to do it but it appears to be working now. 

This is my two cents just in case anyone bumps into the same problem.
 
````
cd patches/vmhgfs
cp -p 16-vmhgfs-f_dentry-kernel-3.19.0-15-tools-9.6.2.patch 16-vmhgfs-f_dentry-kernel-3.13.0-15-tools-9.6.5.patch
````

And I can now see the windows drive mounted at /mnt 
Thanks for all the hard work!!

**Comment by rasa** [comment]
Wow. Running
````
cp -p 16-vmhgfs-f_dentry-kernel-3.19.0-15-tools-9.6.2.patch 16-vmhgfs-f_dentry-kernel-3.13.0-15-tools-9.6.5.patch
````
should not have fixed your issue as the filenames are meaningless, other than the sort order. I have no idea how that fixed your issue.

**Comment by pgiu** [comment]
Hi @rasa I thought that was what solved my problem but It seems that I was wrong. I just assumed that the script would patch depending on the vmware tools version so I decided to copy that patch. I was in a rush trying to make it work so I might have not payed full attention to it. 
I see that you're the owner of the project so feel free to disregard/delete my comment if you find it inappropriate. Anyway, thanks for sharing this.

**Comment by asoc** [comment]
I ran into this issue today with the following:

Ubuntu 12.04 w/ 3.5.0-41
VMware Fusion 7.1.2 and Tools 9.9.3-2759765

The included `dalias` patches weren't being applied because VMware's moved the relevant `d_alias` lines to a `#define hgfs_d_alias()` statement which caused `shared/autoconf/dalias.c` to fail to be patched.

I created a new patch, I've pasted it below so hopefully someone else will get some use out of it. It can probably be rewritten to just replace the file outright without caring about old contents, but it works for me as is...

**patches/vmhgfs/18-vmhgfs-d_alias-kernel-3.18.1-tools-9.9.3.patch**
```diff
diff -uwNr vmhgfs-only.orig/shared/autoconf/dalias.c vmhgfs-only/shared/autoconf/dalias.c
--- vmhgfs-only.orig/shared/autoconf/dalias.c   1969-12-31 16:00:00.000000000 -0800
+++ vmhgfs-only/shared/autoconf/dalias.c        2015-03-18 19:14:44.751231007 -0700
@@ -1,45 +1,21 @@
 /*********************************************************
- * Copyright (C) 2015 VMware, Inc. All rights reserved.
- *
- * This program is free software; you can redistribute it and/or modify it
- * under the terms of the GNU General Public License as published by the
- * Free Software Foundation version 2 and no later version.
- *
- * This program is distributed in the hope that it will be useful, but
- * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
- * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
- * for more details.
- *
- * You should have received a copy of the GNU General Public License along
- * with this program; if not, write to the Free Software Foundation, Inc.,
- * 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
+ * Copyright (C) 2015 Ross Smith II. MIT Licensed.
  *
  *********************************************************/

 #include "compat_version.h"
 #include "compat_autoconf.h"

-#if LINUX_VERSION_CODE < KERNEL_VERSION(3, 19, 0)
-#if LINUX_VERSION_CODE >= KERNEL_VERSION(3, 2, 0)
 #include <linux/dcache.h>
-#include <linux/list.h>

 /*
- * After 3.19.0, the dentry d_alias field was moved. Fedora
- * backported this behavior into a 3.18.0 kernel.
+ * After 3.18.1, the dentry d_alias field was moved to struct d_u.
  *
  * This test will fail on a kernel with such a patch.
  */
 void test(void)
 {
-   struct dentry aliasDentry;
+   struct dentry dentry;

-   INIT_HLIST_NODE(&aliasDentry.d_alias);
+   dentry.d_alias.next = NULL;
 }
-
-#else
-/* Intentionally passes for earlier than 3.9.0 kernels as d_alias is valid. */
-#endif
-#else
-#error "This test intentionally fails on 3.19.0 or newer kernels."
-#endif
```

**Comment by rasa** [comment]
I added your patch in https://github.com/rasa/vmware-tools-patches/commit/cb6bce50f6b3a4e9e8ccc104fca405b0a1dedcdc, but I haven't tested it yet.

**Comment by russt** [comment]
@tuongngoc Thanks! Used your script to patch debian 8.1.0, VMwareTools-9.9.2-2496486.tar.gz
I had to re-run vmware-config-tools.pl manually to re-select hgfs option, compiled fine the second time.

**Comment by dkxl** [comment]
@asoc - Thanks, your patch to dalias.c also works for debian wheezy (3.2.0-4-amd64) and VMwareTools 9.9.3.47419 (build-2759765)

**Comment by LivioCzar** [comment]
@vschoener - thanks for the sinple solution - workes for me with
Windows 7 (Host)
Xubuntu 14.04.03 LTS (Guest)
Kernel 3.13.0-65-generic
VMWare 10.0.3
VMWareTools 9.6.2.31837

**Comment by tracyzhen** [comment]
@vschoener  thanks a lot, it works !

**Comment by vschoener** [comment]
You're welcome :)
