### ISSUE TITLE
vmware-tools-9.9.2 (WS 11.1) compiles neither with 3.13.0-44 nor with 3.16.0-31

### ISSUE THREAD

**Issue by ubremer** [rasa/vmware-tools-patches#30]
Hi,

since my upgrade to Workstation 11.1 a few days ago which seems to come with vmware-tools 9.9.2-1061527 I can get either the unpatched or the patched version of the tools compiled under Ubuntu 14.04 or 14.10 (starting with):

/tmp/modconfig-3213XF/vmhgfs-only/inode.c: In function ‘HgfsPermission’:
include/linux/kernel.h:834:27: error: ‘struct dentry’ has no member named ‘d_alias’

which seems to be caused by:

*** Applying vmblock/03-vmblock.3.12.patch ...
patching file linux/control.c
patching file linux/dentry.c
patching file linux/inode.c
patch unexpectedly ends in middle of line
Hunk #3 succeeded at 221 with fuzz 1.
*** Applying vmblock/04-vmblock-vfs_readlink-kernel-3.15-tools-9.6.2.patch ...
patching file linux/inode.c
Hunk #1 succeeded at 177 (offset -1 lines).
*** Skipping vmhgfs/01-compat_dcache.h.patch: did not apply cleanly
*** Skipping vmhgfs/02-patch_inode.c.patch: did not apply cleanly
*** Applying vmhgfs/03-vmhgfs-3.15-vfs_readlink.patch ...
patching file link.c
Hunk #1 succeeded at 160 (offset 9 lines).
Hunk #2 succeeded at 200 (offset 11 lines).
*** Applying vmhgfs/04-vmhgfs-d_alias-kernel-3.17.7-tools-9.9.0.patch ...
patching file inode.c
*** Skipping vmhgfs/05-vmhgfs-d_count-kernel-3.11-tools-9.6.0.patch: did not apply cleanly
*** Skipping vmhgfs/06-vmhgfs-d_set_type-kernel-3.18.1-tools-9.6.1.patch: did not apply cleanly
*** Skipping vmhgfs/07-vmhgfs-rename_deprecated-kernel-3.18.1-tools-9.6.1.patch: did not apply cleanly
*** Applying vmhgfs/08-vmhgfs-smp_mb_before_clear_bit-3.18-tools-9.9.0.patch ...
patching file page.c
*** Skipping vmhgfs/09-vmhgfs-uid-gid-kernel-3.12-tools-9.6.1.patch: did not apply cleanly
*** Skipping vmhgfs/10-vmhgfs-vfs_readlink-kernel-3.16-tools-9.6.2.patch: did not apply cleanly
*** Skipping vmhgfs/11-vmhgfs-wait_on_bit-kernel-3.17-tools-9.6.2.patch: did not apply cleanly
*** Skipping vmhgfs/12-vmware9.compat_mm.patch: did not apply cleanly
*** Applying vmhgfs/13-vmhgfs-f_dentry-kernel-3.19-tools-9.9.2.patch ...

I'd apprechiate it, if you could have a look at this. Thanks.

Best Regards

Ulf

**Comment by fenris** [comment]
Hi,
Im also having almost the same issue but im using vmware fusion 7.1.1 with VMwareTools-9.9.2-2496486.tar.gz. then executed the untar-and-patch-and-compile.sh

The VMware Host-Guest Filesystem allows for shared folders between the host OS 
and the guest OS in a Fusion or Workstation virtual environment.  Do you wish 
to enable this feature? [yes] 

make: Entering directory '/tmp/modconfig-WoUZKv/vmhgfs-only'
Using kernel build system.
/usr/bin/make -C /lib/modules/3.16.0-31-generic/build/include/.. SUBDIRS=$PWD SRCROOT=$PWD/. \
  MODULEBUILDDIR= modules
make[1]: Entering directory '/usr/src/linux-headers-3.16.0-31-generic'
  CC [M]  /tmp/modconfig-WoUZKv/vmhgfs-only/message.o
  CC [M]  /tmp/modconfig-WoUZKv/vmhgfs-only/dir.o
  CC [M]  /tmp/modconfig-WoUZKv/vmhgfs-only/rpcout.o
  CC [M]  /tmp/modconfig-WoUZKv/vmhgfs-only/cpName.o
  CC [M]  /tmp/modconfig-WoUZKv/vmhgfs-only/link.o
  CC [M]  /tmp/modconfig-WoUZKv/vmhgfs-only/request.o
  CC [M]  /tmp/modconfig-WoUZKv/vmhgfs-only/module.o
  CC [M]  /tmp/modconfig-WoUZKv/vmhgfs-only/page.o
  CC [M]  /tmp/modconfig-WoUZKv/vmhgfs-only/hgfsUtil.o
  CC [M]  /tmp/modconfig-WoUZKv/vmhgfs-only/hgfsEscape.o
  CC [M]  /tmp/modconfig-WoUZKv/vmhgfs-only/file.o
  CC [M]  /tmp/modconfig-WoUZKv/vmhgfs-only/transport.o
  CC [M]  /tmp/modconfig-WoUZKv/vmhgfs-only/inode.o
In file included from ./arch/x86/include/asm/percpu.h:44:0,
                 from ./arch/x86/include/asm/preempt.h:5,
                 from include/linux/preempt.h:18,
                 from include/linux/spinlock.h:50,
                 from include/linux/mmzone.h:7,
                 from include/linux/gfp.h:5,
                 from include/linux/mm.h:9,
                 from include/linux/pagemap.h:7,
                 from /tmp/modconfig-WoUZKv/vmhgfs-only/inode.c:29:
/tmp/modconfig-WoUZKv/vmhgfs-only/inode.c: In function ‘HgfsPermission’:
include/linux/kernel.h:834:27: error: ‘struct dentry’ has no member named ‘d_alias’
  const typeof( ((type *)0)->member ) *__mptr = (ptr); \
                           ^
include/linux/list.h:687:40: note: in expansion of macro ‘container_of’
 #define hlist_entry(ptr, type, member) container_of(ptr,type,member)
                                        ^
include/linux/list.h:698:15: note: in expansion of macro ‘hlist_entry’
     ____ptr ? hlist_entry(____ptr, type, member) : NULL; \
               ^
include/linux/list.h:708:13: note: in expansion of macro ‘hlist_entry_safe’
  for (pos = hlist_entry_safe((head)->first, typeof(*(pos)), member);\
             ^
/tmp/modconfig-WoUZKv/vmhgfs-only/inode.c:1920:7: note: in expansion of macro ‘hlist_for_each_entry’
       hlist_for_each_entry(dentry,
       ^
include/linux/kernel.h:834:48: warning: initialization from incompatible pointer type
  const typeof( ((type *)0)->member ) *__mptr = (ptr); \
                                                ^
include/linux/list.h:687:40: note: in expansion of macro ‘container_of’
 #define hlist_entry(ptr, type, member) container_of(ptr,type,member)
                                        ^
include/linux/list.h:698:15: note: in expansion of macro ‘hlist_entry’
     ____ptr ? hlist_entry(____ptr, type, member) : NULL; \
               ^
include/linux/list.h:708:13: note: in expansion of macro ‘hlist_entry_safe’
  for (pos = hlist_entry_safe((head)->first, typeof(*(pos)), member);\
             ^
/tmp/modconfig-WoUZKv/vmhgfs-only/inode.c:1920:7: note: in expansion of macro ‘hlist_for_each_entry’
       hlist_for_each_entry(dentry,
       ^
In file included from include/linux/compiler-gcc.h:106:0,
                 from include/linux/compiler.h:54,
                 from include/uapi/linux/stddef.h:1,
                 from include/linux/stddef.h:4,
                 from ./include/uapi/linux/posix_types.h:4,
                 from include/uapi/linux/types.h:13,
                 from include/linux/types.h:5,
                 from /tmp/modconfig-WoUZKv/vmhgfs-only/./shared/driver-config.h:71,
                 from /tmp/modconfig-WoUZKv/vmhgfs-only/inode.c:26:
include/linux/compiler-gcc4.h:14:34: error: ‘struct dentry’ has no member named ‘d_alias’
 #define __compiler_offsetof(a,b) __builtin_offsetof(a,b)
                                  ^
include/linux/stddef.h:17:31: note: in expansion of macro ‘__compiler_offsetof’
 #define offsetof(TYPE,MEMBER) __compiler_offsetof(TYPE,MEMBER)
                               ^
include/linux/kernel.h:835:29: note: in expansion of macro ‘offsetof’
  (type *)( (char *)__mptr - offsetof(type,member) );})
                             ^
include/linux/list.h:687:40: note: in expansion of macro ‘container_of’
 #define hlist_entry(ptr, type, member) container_of(ptr,type,member)
                                        ^
include/linux/list.h:698:15: note: in expansion of macro ‘hlist_entry’
     ____ptr ? hlist_entry(____ptr, type, member) : NULL; \
               ^
include/linux/list.h:710:13: note: in expansion of macro ‘hlist_entry_safe’
       pos = hlist_entry_safe((pos)->member.next, typeof(*(pos)), member))
             ^
/tmp/modconfig-WoUZKv/vmhgfs-only/inode.c:1920:7: note: in expansion of macro ‘hlist_for_each_entry’
       hlist_for_each_entry(dentry,
       ^
In file included from include/linux/compiler-gcc.h:106:0,
                 from include/linux/compiler.h:54,
                 from include/uapi/linux/stddef.h:1,
                 from include/linux/stddef.h:4,
                 from ./include/uapi/linux/posix_types.h:4,
                 from include/uapi/linux/types.h:13,
                 from include/linux/types.h:5,
                 from /tmp/modconfig-WoUZKv/vmhgfs-only/./shared/driver-config.h:71,
                 from /tmp/modconfig-WoUZKv/vmhgfs-only/inode.c:26:
include/linux/compiler-gcc4.h:14:34: error: ‘struct dentry’ has no member named ‘d_alias’
 #define __compiler_offsetof(a,b) __builtin_offsetof(a,b)
                                  ^
include/linux/stddef.h:17:31: note: in expansion of macro ‘__compiler_offsetof’
 #define offsetof(TYPE,MEMBER) __compiler_offsetof(TYPE,MEMBER)
                               ^
include/linux/kernel.h:835:29: note: in expansion of macro ‘offsetof’
  (type *)( (char *)__mptr - offsetof(type,member) );})
                             ^
include/linux/list.h:687:40: note: in expansion of macro ‘container_of’
 #define hlist_entry(ptr, type, member) container_of(ptr,type,member)
                                        ^
include/linux/list.h:698:15: note: in expansion of macro ‘hlist_entry’
     ____ptr ? hlist_entry(____ptr, type, member) : NULL; \
               ^
include/linux/list.h:710:13: note: in expansion of macro ‘hlist_entry_safe’
       pos = hlist_entry_safe((pos)->member.next, typeof(*(pos)), member))
             ^
/tmp/modconfig-WoUZKv/vmhgfs-only/inode.c:1920:7: note: in expansion of macro ‘hlist_for_each_entry’
       hlist_for_each_entry(dentry,
       ^
scripts/Makefile.build:257: recipe for target '/tmp/modconfig-WoUZKv/vmhgfs-only/inode.o' failed
make[2]: *** [/tmp/modconfig-WoUZKv/vmhgfs-only/inode.o] Error 1
Makefile:1345: recipe for target '_module_/tmp/modconfig-WoUZKv/vmhgfs-only' failed
make[1]: *** [_module_/tmp/modconfig-WoUZKv/vmhgfs-only] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-3.16.0-31-generic'
Makefile:120: recipe for target 'vmhgfs.ko' failed
make: *** [vmhgfs.ko] Error 2
make: Leaving directory '/tmp/modconfig-WoUZKv/vmhgfs-only'

**Comment by anodynos** [comment]
I have the same problem with `VMwareTools-9.9.2-2496486.tar.gz` on **Kubuntu 14.10** (kernel 3.16.0-31) both [patched](https://gist.github.com/anodynos/5c51b82e7589669c84cc) and [unpatched](https://gist.github.com/anodynos/830718867daf1e13fa3e).

**Comment by anodynos** [comment]
Its solved, without even needing the patch - see https://github.com/rasa/vmware-tools-patches/issues/29#issuecomment-76469889
