### ISSUE TITLE
VMware Player

### ISSUE THREAD

**Issue by Melab** [rasa/vmware-tools-patches#36]
What version number do I use for VMware Player 6.0.5? All I see is stuff for VMware Workstation and VMware Fusion.

**Comment by rasa** [comment]
https://softwareupdate.vmware.com/cds/vmw-desktop/player/6.0.5/2443746/linux/packages/
indicates VMware Tools version 9.6.4 is what you want, but I don't see that version available at
https://softwareupdate.vmware.com/cds/vmw-desktop/fusion/ . Try either the latest, [VMwareTools-9.9.2-2496486.tar.gz](https://softwareupdate.vmware.com/cds/vmw-desktop/fusion/7.1.1/2498930/packages/com.vmware.fusion.tools.linux.zip.tar) (VMware Fusion 7.1.1 & Workstation 11.1.0), or the next one after 9.6.4 that is available, which is [VMwareTools-9.8.3-2075148.tar.gz](https://softwareupdate.vmware.com/cds/vmw-desktop/fusion/7.0.0/2075534/packages/com.vmware.fusion.tools.linux.zip.tar) (VMware Fusion 7.0.0)

**Comment by rasa** [comment]
Or try [VMwareTools-9.6.2-1688356.tar.gz](https://softwareupdate.vmware.com/cds/vmw-desktop/fusion/6.0.3/1747349/packages/com.vmware.fusion.tools.linux.zip.tar) (VMware Fusion 6.0.3/4/5 & Workstation 10.0.2/3/4), as it worked here: https://github.com/rasa/vmware-tools-patches/issues/35

**Comment by liayn** [comment]
Why not upgrading to Player 7 and use latest tools provided with it?
