### ISSUE TITLE
patch vmblock/03-vmblock.3.12.patch unexpectedly ends in middle of line

### ISSUE THREAD

**Issue by joca-bt** [rasa/vmware-tools-patches#37]
While applying Patch vmblock/03-vmblock.3.12.patch the following message is shown:

```
...
*** Applying vmblock/03-vmblock.3.12.patch ...
patching file linux/control.c
patching file linux/dentry.c
patching file linux/inode.c
patch unexpectedly ends in middle of line
...
```

Using VMware Workstation 11.1.0 build 2496824 and VMware Tools 9.9.2 build 2496486.

**Comment by rasa** [comment]
Somehow the patch from 
http://dominator008.com/crate/vmblock-3.12-patch
got changed slightly. This should fix it.
