### ISSUE TITLE
Ubuntu 15.04 (Kernel 3.19.0-15) - NOT all the patches have been applied cleanly

### ISSUE THREAD

**Issue by alekseYY** [rasa/vmware-tools-patches#40]
alekseYY@ubuntu:~/apps/vmware-tools-patches$ sudo ./untar-and-patch.sh
untar.sh: Patching ./VMwareTools-9.6.2-1688356.tar.gz
=== Patching ./VMwareTools-9.6.2-1688356.tar.gz ...

*** Applying vmblock/01-vmblock.3.10.patch ...
patching file linux/control.c
*** Applying vmblock/02-vmblock.3.11.patch ...
patching file linux/file.c
*** Applying vmblock/03-vmblock.3.12.patch ...
patching file linux/control.c
patching file linux/dentry.c
patching file linux/inode.c
*** Applying vmblock/04-vmblock-vfs_readlink-kernel-3.15-tools-9.6.2.patch ...
patching file linux/inode.c
Hunk #1 succeeded at 177 (offset -1 lines).
*** Applying vsock/01-vsock-sk_data_ready-kernel-3.15-tools-9.6.2.patch ...
patching file linux/notify.c
patching file linux/notifyQState.c
*** Applying vmhgfs/01-compat_dcache.h.patch ...
patching file shared/compat_dcache.h
*** Skipping vmhgfs/02-patch_inode.c.patch: did not apply cleanly
*** Applying vmhgfs/03-vmhgfs-3.15-vfs_readlink.patch ...
patching file link.c
*** Skipping vmhgfs/04-vmhgfs-d_alias-kernel-3.18.1-tools-9.9.0.patch: did not apply cleanly
*** Skipping vmhgfs/05-vmhgfs-d_count-kernel-3.11-tools-9.6.0.patch: did not apply cleanly
*** Skipping vmhgfs/06-vmhgfs-d_set_type-kernel-3.18.1-tools-9.6.1.patch: did not apply cleanly
*** Applying vmhgfs/07-vmhgfs-rename_deprecated-kernel-3.18.1-tools-9.6.1.patch ...
patching file shared/vm_assert.h
*** Applying vmhgfs/08-vmhgfs-smp_mb_before_clear_bit-3.18-tools-9.9.0.patch ...
patching file page.c
Hunk #1 succeeded at 1450 (offset -228 lines).
*** Skipping vmhgfs/09-vmhgfs-uid-gid-kernel-3.12-tools-9.6.1.patch: did not apply cleanly
*** Applying vmhgfs/10-vmhgfs-vfs_readlink-kernel-3.16-tools-9.6.2.patch ...
patching file file.c
patching file link.c
patching file shared/compat_fs.h
*** Applying vmhgfs/11-vmhgfs-wait_on_bit-kernel-3.17-tools-9.6.2.patch ...
patching file page.c
*** Skipping vmhgfs/12-vmware9.compat_mm.patch: did not apply cleanly
*** Skipping vmhgfs/13-vmhgfs-f_dentry-kernel-3.19-tools-9.9.2.patch: did not apply cleanly
*** Applying vmhgfs/14-vmhgfs-d_alias-kernel-3.18.1-tools-9.6.2.patch ...
patching file inode.c
patching file Makefile.kernel
patching file shared/autoconf/d_alias.c
*** Applying vmhgfs/15-vmhgfs-bdi-kernel-4.0-tools-9.9.2.patch ...
patching file filesystem.c
Hunk #1 succeeded at 388 (offset 2 lines).
Hunk #2 succeeded at 441 (offset 2 lines).
patching file module.h
patching file super.c
*** Applying vmci/01-vmware9.k3.8rc4.patch ...
patching file linux/driver.c
Reversed (or previously applied) patch detected!  Assuming -R.
Hunk #1 succeeded at 128 with fuzz 1 (offset 4 lines).
Hunk #2 succeeded at 1747 (offset -3 lines).
Hunk #3 succeeded at 1975 (offset -3 lines).

**Comment by egbokalaka** [comment]
I get similar (maybe identical) output with kernel Ubuntu 14.04.2 /3.16.0-36-generic on Ubuntu 14.04.2 on VMware Fusion 7.1.1. Thanks for all your hard work.

**Comment by altendky** [comment]
I just made [this patch](https://gist.github.com/altendky/5b0b0a645bb1c20e0d35) and it worked for me.  Hopefully it can help you out as well.  If so, anyone is certainly welcome to submit it.

**Comment by altendky** [comment]
Also note that not all patches will apply cleanly.  There are redundant patches for different versions so some are expected to fail in each case.

**Comment by rasa** [comment]
@altendky: https://gist.github.com/altendky/5b0b0a645bb1c20e0d35 is very similar to https://github.com/rasa/vmware-tools-patches/blob/master/patches/vmhgfs/13-vmhgfs-f_dentry-kernel-3.19-tools-9.9.2.patch . Please submit it as `patches/vmhgfs/16-vmhgfs-f_dentry-kernel-3.19.0-15-tools-9.6.2.patch`. Thanks.

**Comment by rasa** [comment]
Fixed in #44
