### ISSUE TITLE
Fedora 21 Kernel 4.0.4, empty files via hgfs

### ISSUE THREAD

**Issue by liayn** [rasa/vmware-tools-patches#50]
Writing files via hgfs results in empty files in the host system. The files and folders are created, but all of them are empty.

**Comment by patmans** [comment]
This is worse than it might sound - I effectively erased one of my files by editing it :-(

I assume this affects all 4.x kernels. I'm running with 3.19 for now to avoid the problem

**Comment by liayn** [comment]
Happened to me as well. Luckily it was in a git repo on the host. I remember having had the same issue with some 3.19 version as well, but don't know the exact version anymore.

**Comment by liayn** [comment]
Updated to VMware Player 7.1.2 build-2780323 (including tools 9.9.3)
Still the same issue.

Writing to a file seems to work inside the guest (Fedora), but the result does never appears in my host (Win).

```
echo Test > test.txt
cat test.txt # echos Test
```

The `test.txt` in Win is empty though.
After reboot the same file is empty in the guest as well.

It looks like some intermediate buffer is never flushed.

**Comment by liayn** [comment]
Maybe this is related to  #38 somehow.

**Comment by liayn** [comment]
#39 modified for 9.9.3 solves the issue.

**Comment by patmans** [comment]
Thanks for pointing that out, I updated to the new patch and it's working fine now.
