### ISSUE TITLE
Shared Folders problem with Ubuntu 15.10

### ISSUE THREAD

**Issue by laktak** [rasa/vmware-tools-patches#74]
I have the same issue as #54 with Vmware 7.1 and Ubuntu 15.10.

Manually running 
- `download-tools.sh 8.0.0`
- `untar-and-patch.sh`
- and `vmware-install.pl` instead of `compile.sh`

fixed it.

**Comment by joswart** [comment]
I can confirm the above method worked for me as well.

**Comment by matis** [comment]
works for me, if you have installed vm-tools via apt-get you have to remove etc/vmware-tools

**Comment by hurda** [comment]
vmware-tools being problematic in 15.10 is a known issue, even in the latest versions:
http://pubs.vmware.com/Release_Notes/en/workstation/12pro/workstation-1201-release-notes.html#knownissues

**Comment by nxadm** [comment]
I agree. It didn't work for me for Workstation 11 on Windows as host and Ubuntu 15.10 as guest. However the VMWare tools developer has good news:

"There are also a few other fixes now going into the same release and it will enable the vmhgfs kernel driver to be built and work correctly with Linux 4.2 kernels which are used currently with Fedora 22 and Ubuntu 15.10."

https://communities.vmware.com/message/2550883

**Comment by liayn** [comment]
Seems to be related to #73

**Comment by yaochiqkl** [comment]
Same issue with with Ubuntu 15.10 and VMware 12.0.0 
@laktak Sorry, but I'm a newbie, don't know how to ran them . Could you offer more details? Thx

**Comment by laktak** [comment]
@yaochiqkl see https://github.com/rasa/vmware-tools-patches#quick-start and replace the commands

**Comment by Shravan2x** [comment]
Can confirm that this fix works for 15.04LTS on Workstation 12.

**Comment by StayTherapy** [comment]
Same issue with `open-vm-tools` latest version and Ubuntu 15.10 with VMware Workstation 11.
I resolve this proplem like this:
1. Update VMware Workstation to Version `11.1.4 build-3848939`
2. reomve `open-vm-tools` and `open-vm-tools-dkms`
3. Install the `VMware Tools 9.9.5 build-3735633 for Linux`

and no path need.
