### ISSUE TITLE
VMWare Workstation 12

### ISSUE THREAD

**Issue by LukB4ULeap** [rasa/vmware-tools-patches#81]
Has Packer been tested on VMWare Workstation Pro 12?

**Comment by dragon788** [comment]
@LukB4ULeap This repository is only for VMware Tools patches, not Packer. If you are using this in conjuction with Packer like I am that's great, but whether Packer supports the new VMware Workstation is probably better asked at https://github.com/mitchellh/packer or on their Google Groups.
