### ISSUE TITLE
./compile.sh issue

### ISSUE THREAD

**Issue by Maddog99** [rasa/vmware-tools-patches#87]
I am trying to install the patch for VMware Tools 9.9.0 build-2304977.
I am using ubuntu 12.04 with VM workstation 11. 
When I execute the 
$ sudo ./compile.sh 
I get the following
Usage: ./vmware-install.pl [[-][-]d[efault]]
default: Automatically answer questions with the proposed answer.
[[-][-]prefix=<path to install product: bin, lib, doc>]    Put the installation
at <path> instead of the default location.  This implies '--default'.
--clobber-kernel-modules=<module1,module2,...>    Forcefully removes any VMware
related modules installed by any other installer and installs the modules 
provided by this installer.  This is a comma separated list of modules.

In looking at the compile.sh, it appears to have the proper arguments. 

Any suggestions on what I am probably doing incorrectly?

**Comment by sykesm** [comment]
@Maddog99 you appear to be hitting #86 as the usage doesn't include the `force-install` option.

**Comment by rasa** [comment]
Since #86 has been merged in, I'm gonna close this. Please re-open if it's still an issue.
